version: "3.8"

services:
  product-service:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - hypercircuit-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hypercircuit-net

volumes:
  mongo-data:

networks:
  hypercircuit-net:
    driver: bridge
