name: Run Tests - Product Service

on:
  push:
    branches: [ main ]
    paths:
      - 'services/product-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/product-service/**'

jobs:
  product-service-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/product-service

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Ensure jest is executable
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests
        run: npm test
